//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yoonite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountRefreshToken
    {
        public System.Guid Id { get; set; }
        public System.Guid AccountId { get; set; }
        public string RefreshToken { get; set; }
        public string ProtectedTicket { get; set; }
        public System.DateTimeOffset DateIssued { get; set; }
        public System.DateTimeOffset DateExpired { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
