//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yoonite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ReviewedByAccountId { get; set; }
        public int HResult { get; set; }
        public string Source { get; set; }
        public string ExceptionType { get; set; }
        public string ExceptionMessage { get; set; }
        public string InnerExceptionMessage { get; set; }
        public string StackTrace { get; set; }
        public string Parameters { get; set; }
        public bool IsReviewed { get; set; }
        public string ReviewedComments { get; set; }
        public Nullable<System.DateTimeOffset> DateReviwed { get; set; }
        public System.DateTimeOffset DateCreated { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
