//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yoonite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSkillCrossLink
    {
        public System.Guid Id { get; set; }
        public System.Guid ProjectId { get; set; }
        public System.Guid SkillId { get; set; }
        public System.DateTimeOffset DateCreated { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
