//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yoonite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectSkillCrossLinks = new HashSet<ProjectSkillCrossLink>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid AccountId { get; set; }
        public Nullable<System.Guid> ProjectImageStorageId { get; set; }
        public string ProjectName { get; set; }
        public string CompanyName { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public bool CanBeRemote { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTimeOffset DateCreated { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectSkillCrossLink> ProjectSkillCrossLinks { get; set; }
    }
}
